name: ci-pipeline
#reusable workflows to be call for toher workflows
on:
  workflow_call: 
    secrets:
      SONAR_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
         required: true
      DOCKERHUB_TOKEN:
         required: true

jobs:
  unit-tests:
    name: Running Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Test
        run: |
          mkdir reports/
          pytest -v \
            --junitxml=reports/unit-test-results.xml \
            --cov=. \
            --cov-report=xml:reports/coverage.xml \
            --cov-report=term-missing

      - name: Upload code coverage report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: reports/

  codeql:
    name: CodeQL Security Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      matrix:
        language: ['python']      # ← sin espacios extra
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "security"

  SonarQube:                      # ← dentro de jobs: (mismo nivel que los otros)
    name: SonarQube
    runs-on: ubuntu-latest  
    needs: unit-tests  # ← minúsculas
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Download Coverage Report
        uses: actions/download-artifact@v4
        with:
          name: unit-test-report
          path: reports/

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    name: Build Image
    runs-on: ubuntu-latest
    needs: [codeql, SonarQube]
    if: success()
    outputs:
      image-tags: ${{ steps.vars.outputs.image-tags }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Generate Image tags
        id: vars
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          IMAGE_TAGS="${{ github.run_id }}-${SHORT_SHA}"
          echo "image-tags=$IMAGE_TAGS" >> $GITHUB_OUTPUT

      - name: Build image (no push)
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: thinkynx_app:${{ steps.vars.outputs.image-tags }}
          load: true
      
      - name: Save Docker Image as artifact
        run: docker save thinkynx_app:${{ steps.vars.outputs.image-tags }} -o thinkynx_app.tar
      
      - name: Upload Docker image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: thinkynx_app_image
          path: thinkynx_app.tar

  publish-dockerhub:
    name: publish to docker hub 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download the image
        uses: actions/download-artifact@v4
        with: 
          name: thinkynx_app_image
          path: .
      - name: Load Docker Image
        run: docker load -i thinkynx_app.tar

      - name: Docker Login
        uses: docker/login-action@v3.0.0 # docker login -u DOCKERHUBU_USER -P DOCKERHUB_PASSWORD
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag Image
        run: |
          IMAGE_TAG="${{ needs.build.outputs.image-tags }}"
          DOCKERHUB_USER=$(echo "${{ secrets.DOCKERHUB_USERNAME }}" | tr '[:upper:]' '[:lower:]')
          docker image tag thinkynx_app:$IMAGE_TAG $DOCKERHUB_USER/thinkynx_app:$IMAGE_TAG
      - name: Push Image
        run: |
          IMAGE_TAG="${{ needs.build.outputs.image-tags }}"
          DOCKERHUB_USER=$(echo "${{ secrets.DOCKERHUB_USERNAME }}" | tr '[:upper:]' '[:lower:]')
          docker image push $DOCKERHUB_USER/thinkynx_app:$IMAGE_TAG


  publish-ghcr:
    name: publish to Github Container Registry
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download the image
        uses: actions/download-artifact@v4
        with: 
          name: thinkynx_app_image
          path: .
      - name: Load Docker Image
        run: docker load -i thinkynx_app.tar

      - name: Docker TO ghcr
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # ✅ Correct
      - name: Tag Image
        run: |
          IMAGE_TAG="${{ needs.build.outputs.image-tags }}"
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker image tag thinkynx_app:$IMAGE_TAG ghcr.io/$REPO_OWNER/thinkynx_app:$IMAGE_TAG

      - name: Push Image
        run: |
          IMAGE_TAG="${{ needs.build.outputs.image-tags }}"
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker image push ghcr.io/$REPO_OWNER/thinkynx_app:$IMAGE_TAG
