name: Deployment using kubectl

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: 'Deployment Environment (e.g., STAGING, PRODUCTIONd).'
        required: true 
        type: string
      IMAGE_NAME:
        required: true
        type: string
    secrets:
      KUBECONFIG:
        required: true

jobs:
  deploy:
    environment: ${{inputs.ENVIRONMENT}}
    env:
      NAMESPACE: ${{ vars.NAMESPACE }}
    runs-on: github-actions-scaleset-demo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          kubectl version
          kubectl get nodes

      - name: Install yq
        run: |
          sudo curl -L https://github.com/mikefarah/yq/releases/download/v4.35.1/yq_linux_amd64 -o /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          yq --version

      - name: Update image name in deployment yaml
        run: |
          IMAGE_TAGS="${{ github.run_id }}-${GITHUB_SHA::7}"
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          export IMAGE="ghcr.io/${REPO_OWNER}/thinkynx_app:${IMAGE_TAGS}"
          yq e ' .spec.template.spec.containers[0].image = strenv(IMAGE)' manifest/deployment.yaml -i
          cat manifest/deployment.yaml

      - name: Create namespace if not exists
        run: |
          kubectl get namespace $NAMESPACE || kubectl create namespace $NAMESPACE

      - name: Deploy to kubernetes cluster
        run: |
          kubectl apply -f manifest/ -n $NAMESPACE

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/thinkynxapp-deploy -n $NAMESPACE
          kubectl get all -n $NAMESPACE
